id: I570A02E2
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T13:55:42+00:00'
last_modified: '2022-06-09T07:24:48.498175+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00EGS1017422
  title: དྲི་བཟང་ཐུལ་བའི་སྨན་ལྗོངས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    B811:
      image_group_id: I1PD28032
      title: Volume 1 of dri bzang thul ba'i sman ljongs
      total_pages: 380
      order: 1
      base_file: B811.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
