id: P007913
initial_creation_type: ocr
source_metadata:
  id: bdr:W00EGS1017422
  title: དྲི་བཟང་ཐུལ་བའི་སྨན་ལྗོངས
  author: ''
  volumes:
    9f06c47ede0140be892281d64b1aabf2:
      image_group_id: I1PD28032
      title: ''
      volume_number: 1
      total_pages: 380
ebook_metadata:
  title: དྲི་བཟང་ཐུལ་བའི་སྨན་ལྗོངས
  author: ''
  sku: P007913
  cover: cover.jpg
  layers:
  - pagination
